[package]
name = "youtube_dl"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
failure = "0.1"