[package]
name = "youtube_dl"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
edition = "2018"

[dependencies]
schemafy = "0.5.0"
serde = {version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
