[package]
name = "youtube_dl"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]
edition = "2018"
description = "Runs youtube-dl and parses its JSON output."
license = "MIT/Apache-2.0"
repository = "https://github.com/GyrosOfWar/youtube-dl-rs"
homepage = "https://github.com/GyrosOfWar/youtube-dl-rs"
categories = ["multimedia::video"]
keywords = ["youtube-dl", "youtube"]

[dependencies]
serde = {version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
failure = "0.1"