name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.1

      - name: Install youtube-dl and yt-dlp
        run: pip install youtube-dl yt-dlp

      - name: Install rustfmt
        run: rustup component add rustfmt

      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo hack test --each-feature --no-dev-deps
